// src/components/Loading.svelte
<script>
	import { onMount } from "svelte";
	let text = "";
	onMount(() => {
		const array = [
			"Quickly edit your last sent message! Type 's/[what to replace]/[what to replace with]'.",
			"Press 0 at any point in message history to scroll to the latest.",
			"This application is open-sourced at https://github.com/cyan-2048/Discord4KaiOS",
			"We have a dedicated Discord server for support on this application! Check it out in Settings.",
      			"Don't ask for ETAs. No 'When will A arrive?'. We're all humans.",
      			"never gonna give you up",
      			"We're connecting to Discord's gateways to retrieve account info, server list and message history. Be patient!",
			"This application is built on Frank128's prototype of Discord for Windows XP, coded in several nights."
		]; // wanna add something? just tell cyan in discord
		text = array[new Date() % array.length];
	});
</script>

<div id="loading">
	<img src="/css/loading.png" alt />
	<div id="dyk">DID YOU KNOW</div>
	<div id="fact">{text}</div>
</div>

<style>
	#loading {
		width: 100vw;
		height: 100vh;
		position: absolute;
		top: 0;
		left: 0;
		background-color: #2f3136;
		text-align: center;
	}
	#loading img {
		width: 200px;
		height: 200px;
		margin: 12px 0;
		display: inline-block;
	}
	#dyk {
		font-size: 12px;
		margin-top: -35px;
		font-weight: 600;
		margin-bottom: 8px;
	}
	#fact {
		font-size: 16px;
		height: 75px;
	}
</style>

// src/routes/Loading/Loading.tsx
import { Markdown } from "@components/Markdown";
import { h, Fragment } from "preact";
import { useEffect, useState } from "preact/hooks";
import "./style.scss";

const getRandomText = randomNoRepeats([
	"Quickly edit your last sent message! Type 's/[what to replace]/[what to replace with]'.",
	`Press 0 at any point in message history to scroll to the latest.`,
	"This application is open-sourced at https://github.com/cyan-2048/Discord4KaiOS",
	"We have a dedicated Discord server for support on this application! Check it out in Settings.",
	"Don't ask for ETAs. No 'When will *something* arrive?'. We're all humans.",
	"never gonna give you up",
	"We're connecting to Discord's gateways to retrieve account info, server list and message history. Be patient!",
	"This app is a fork of Frank128's Discord-KaiOS-Unofficial.",
	"The app 99% only connects to discord's servers!",
	"The Discord API Docs gives you enough information to create your own Discord Client.",
]);

function randomNoRepeats(array: any[]) {
	var copy = array.slice(0);
	return function () {
		if (copy.length < 1) {
			copy = array.slice(0);
		}
		var index = Math.floor(Math.random() * copy.length);
		var item = copy[index];
		copy.splice(index, 1);
		return item;
	};
}

export default function Loading(props: any) {
	const [text, setText] = useState(getRandomText());

	useEffect(() => {
		const interval = setInterval(() => {
			setText(getRandomText());
		}, 4000);

		return () => clearInterval(interval);
	});

	return (
		<div class="Loading">
			<img src="/css/loading.png" />
			<div id="dyk">DID YOU KNOW</div>
			<div id="fact">{typeof text == "string" ? <Markdown text={text} /> : <>{text}</>}</div>
		</div>
	);
}
